### ISSUE TITLE
Sample mapping and template files missing?

### ISSUE THREAD

**Issue by ferdinandosimonetti** [thombashi/elasticsearch-faker#1]
Hello, I'm an Elasticsearch "newbie" and I'm looking for a tool for filling my test ES instance with logs, to be subsequently queried through Kibana.
I've found your tool, but I'm quite stuck now, because I have no clue about how to generate a meaningful mapping and/or template file:

```Usage: elasticsearch-faker generate [OPTIONS] HOST

  Generate fake data and put it to Elasticsearch

Options:
  --index NAME           Name of an index to create. Defaults to 'test_index'.
  --mapping PATH         Path to a mapping file.
  --template PATH        Path to a faker template file.``````

**Comment by thombashi** [comment]
Hello,

`--mapping` option can be specify mapping of a creating index:
see also: https://www.elastic.co/guide/en/elasticsearch/reference/current/explicit-mapping.html
You can omit `--mapping` option if you would not need explicit mapping (`elasticsearch-faker 0.1.0 or later`).

`--template` option needs to specify a creating document template file with jinja format.
For example:

```
{
  "name": "{{ user_name }}",
  "userId": {{ random_number }},
  "createdAt": "{{ date_time }}",
  "body": "{{ text }}",
  "ext": "{{ word }}",
  "blobId": "{{ uuid4 }}"
}
```

`{{ XXX }}` is called provider.
You can use the available provider listed by `elasticsearch-faker provider list`/`elasticsearch-faker provider example`.

`elasticsearch-faker generate` execution example:

```
$ elasticsearch-faker generate --template doc_template.jinja2 localhost:9200 -n 1000
document generator #0: 100%|█████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 590.53docs/s]
[INFO] generate 1000 docs to test_index

[Results]
target index: test_index
completed in 2.5 secs
current store.size: 0.0 MB
current docs.count: 1,000
generated store.size: 0.0 MB
generated docs.count: 1,000
generated docs/secs: 395.3
bulk size: 200
$ curl -sS localhost:9200/test_index/_search | jq .hits.hits[:3]
[
  {
    "_index": "test_index",
    "_type": "_doc",
    "_id": "4bdd73c0-7744-4c6f-9736-50e3e8515f1c-0",
    "_score": 1,
    "_source": {
      "name": "jennifer17",
      "userId": 56561230,
      "createdAt": "2009-07-17T06:31:04.000+0000",
      "body": "Present blue happen thus miss toward. Itself race so successful build real beyond score. Look different she receive.Compare miss federal lawyer. Herself prevent approach east.",
      "ext": "course",
      "blobId": "c35769a9-3468-43fc-93c7-3c2f27ec9f64"
    }
  },
  {
    "_index": "test_index",
    "_type": "_doc",
    "_id": "88238d96-5ecc-4639-bb8f-c3f816027560-0",
    "_score": 1,
    "_source": {
      "name": "dnicholson",
      "userId": 457,
      "createdAt": "2008-08-29T22:14:43.000+0000",
      "body": "I sit another health president bring. Very expect international television job parent into.Authority read few stock. International hope yard left measure.Player them get move.",
      "ext": "trial",
      "blobId": "e43faf58-9b66-4a43-b1b7-7540b3996cde"
    }
  },
  {
    "_index": "test_index",
    "_type": "_doc",
    "_id": "0282b2b7-f83d-4f45-a27e-6040e22213e9-0",
    "_score": 1,
    "_source": {
      "name": "leslie11",
      "userId": 111552,
      "createdAt": "1995-12-17T15:28:50.000+0000",
      "body": "First say three toward. That wall trip.Sound who prove order painting me. However see spring. Try check public fear.Avoid whether operation movement. Lead grow color may up purpose.",
      "ext": "up",
      "blobId": "4af95df0-4e5b-434f-94a3-73e7698db70b"
    }
  }
]
```

**Comment by hieu-ht** [comment]
Hi, I'm an Elasticsearch "newbie", too. I try to find the path of the mapping file in a docker container Elastic search 8.1 to copy it to the host but can't (I already created mapping before). The reason is I want to generate mock data following my mapping. Do you have any suggestions? Thank you for your help

**Comment by thombashi** [comment]
@hieu-ht 
Hi,

I'm not exactly sure what your situation.
You can execute the tool without `--mapping` option.
Or, you can use [Get mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html) if you mean that you would like to get the mapping from an existing index.

**Comment by TirushV** [comment]
What if the elastic search cluster has authentication username and password how do we pass it in elasticsearch-faker?
