### ISSUE TITLE
int() argument must be a string, a bytes-like object or a real number, not 'TextApiResponse'

### ISSUE THREAD

**Issue by Leventi** [thombashi/elasticsearch-faker#3]
Get error when try apply example
`elasticsearch-faker generate --template doc_template.jinja2 localhost:9200 -n 1000`

error
`  File "C:\Users\user\dev\elastic_dev\venv\lib\site-packages\elasticsearch_faker\_es_client.py", line 151, in count_docs
    return int(self.__es.cat.count(index=index_name, params={"h": "count"}))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'TextApiResponse'
`

**Comment by draentropia** [comment]
The same here. Installed using pip3 in rocky linux 8.6 on 26th july 2022 using the jinja2 template from the README file.

**Comment by rivaldyarif** [comment]
same here, is there any update on this issue?

**Comment by thombashi** [comment]
Thank you for your report.

I can not reproduce the error.
Please let me know the following information:

- Environment information:
  - OS
  - Python version
  - elasticsearch-faker version
  - Elasticsearch version
  - Elasticsearch-py version
- Options of Elasticsearch

**Comment by dtrinhxlong** [comment]
the same here, with infos:
- OS: MacOS
- Python version:
pip 22.3.1 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)
- Elasticsearch version install from docker image https://hub.docker.com/_/elasticsearch:
Version: 8.5.2, Build: docker/a846182fa16b4ebfcc89aa3c11a11fd5adf3de04/2022-11-17T18:56:17.538630285Z, JVM: 19.0.1
- Elasticsearch-faker version:
elasticsearch-faker 0.2.0

pls help me @thombashi , thank you~

**Comment by dtrinhxlong** [comment]
i fixed this issuse with below step:
- vim /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/elasticsearch_faker/_es_client.py
- search keyworkd: count_docs
- lookup change to:
def count_docs(self, index_name: str) -> int:
        return 0 #int(self.__es.cat.count(index=index_name, params={"h": "count"}))

thank you~

**Comment by vfontanella** [comment]
I have a problem when trying to delete an index:
  File "/opt/homebrew/lib/python3.10/site-packages/elasticsearch_faker/_es_client.py", line 151, in count_docs
    return int(self.__es.cat.count(index=index_name))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'TextApiResponse'
That even with the change above.
Any help will be appreciated.

**Comment by thombashi** [comment]
Thank you for your information.
The problem was fixed at `elasticsearch 0.3.0`
