### ISSUE TITLE
Error trying to connect to a https endpoint.

### ISSUE THREAD

**Issue by vfontanella** [thombashi/elasticsearch-faker#4]
I found that it doesn't connect to the endpoint when trying to connect though https.
My workaround was changing the site-packages/elasticsearch_faker/_es_client.py file

modifying the create_es_client function adding the verify_certs and basic_auth parameters.
Maybe I'm missing something and there is another way to do that.
Any comment will be appreciated.

**Comment by skypad123** [comment]
had the same issue when connecting to elasticsearch cloud. hopefully, there is an update for auth support.

**Comment by thombashi** [comment]
Thank you for your report.
You can connect to a https endpoint with `elasticsearch-faker 0.3.0`.
Please check the README or help message of the command.
